server:
  service:
    ## If false, no Service will be created for the Prometheus server
    ##
    enabled: true
    annotations: 
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-name: "prometheus"
    labels: {}
    clusterIP: ""

    ## List of IP addresses at which the Prometheus server service is available
    ## Ref: https://kubernetes.io/docs/concepts/services-networking/service/#external-ips
    ##
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 80
    sessionAffinity: None
    type: LoadBalancer

  persistentVolume:
    accessModes:
      - ReadWriteOnce
    enabled: true
    mountPath: /data
    size: 20Gi
    storageClass: gp2